# Generated by Django 5.0.14 on 2025-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='extra_genres',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
