# Generated by Django 5.0.14 on 2025-04-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0002_remove_book_extra_genres_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, db_column='AuthorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore_sqlserver_django.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, db_column='PublisherID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore_sqlserver_django.publisher'),
        ),
    ]
