# Generated by Django 5.0.14 on 2025-04-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0003_alter_book_author_alter_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookGenre',
        ),
    ]
