# Generated by Django 5.0.14 on 2025-04-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0004_delete_bookgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='bookstore_sqlserver_django.user'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
