# Generated by Django 5.0.14 on 2025-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0005_user_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_column='IsAdmin', default=False),
        ),
    ]
