# Generated by Django 5.0.14 on 2025-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, db_column='Password', max_length=128, null=True),
        ),
    ]
