# Generated by Django 5.0.14 on 2025-04-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
