# Generated by Django 5.0.14 on 2025-04-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0009_rename_customer_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='TotalAmount', decimal_places=2, max_digits=10, null=True),
        ),
    ]
