# Generated by Django 5.0.14 on 2025-04-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0010_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='bookstore_sqlserver_django.order'),
        ),
    ]
