# Generated by Django 5.0.14 on 2025-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0011_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='Users_Email_f4e742_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='Users_FirstNa_b287f7_idx'),
        ),
    ]
