# Generated by Django 5.0.14 on 2025-04-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_sqlserver_django', '0012_user_users_email_f4e742_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='Users_Email_f4e742_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='Users_FirstNa_b287f7_idx',
        ),
    ]
